### ISSUE TITLE
Ticket: EB-147418: Add New Marketing Tools MLP to Key Footers

### ISSUE THREAD

**Issue by trinitychristiana-eb** [trinitychristiana-eb/task-tracker#78]
[Jira Link](https://jira.evbhome.com/browse/EB-147418)

- [ ] Read the ticket
   - If you have any questions add them as a comment to this issue ticket before asking them (If the ticket is a general question feel free to create a question ticket and reference this issue in it)
   - After you've read through it and have come up with questions ask them
   - When they are answered document them bellow where you put the question (in the comments to this issue or another issue)
- [ ] Now do you understand what the ticket is asking of you?
- [ ] Fill in the next step with what steps you will need to take to finish the ticket. Feel free to update them as you solve the ticket as well
- [ ] Solve Ticket
   - [ ] FInd where the Homepage footer lives in the codebase (which repo?)
   - [ ] Find the Plan Events section of the footer
   - [ ] Add the link to the footer
   - [ ] Make sure it looks like the rest of the footer
- [ ] [Create PR]()
- [ ] Create QA steps for the ticket **Remove this if unnecessary**
- [ ] Put PR in #seo-needs-you
- [ ] Get Reviews **Add any comments made to this ticket as a comment as well**
   - [ ] Delaine
   - [ ] Justin
   - [ ] Olivia
- [ ] Merge it
- [ ] Say ready for QA in #seo-needs-you **Remove this if unnecessary**

**Comment by trintiychristiana-eb** [comment]
# Question: What is considered the homepage?

TRINITY: Is https://www.eventbrite.com/ the homepage? The ticket says "Put this URL under Plan Events listed as 'Event Marketing Tools' on the homepage footer" but https://www.eventbrite.com/ uses the skinny "site-footer" and does not have a Plan Event's Section. Would this be a better question for Matthew because he wrote the ticket? If so then I'll just ask him on Monday during standup.
